# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-25 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyminer',
            fields=[
                ('probeid', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('nmtsi', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True)),
                ('potential_regulatory_lineage', models.CharField(blank=True, default='', max_length=2)),
                ('atsi', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True)),
                ('potential_tissue_specificity', models.CharField(blank=True, default='', max_length=3)),
                ('hd0', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True)),
                ('hd3', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True)),
                ('hd6', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True)),
                ('hd10', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True)),
                ('kd0', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True)),
                ('kd3', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True)),
                ('kd6', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True)),
                ('kd10', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True)),
                ('nd0', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True)),
                ('nd3', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True)),
                ('nd6', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True)),
                ('nd10', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True)),
                ('specific_regulatory_linearge', models.CharField(blank=True, default='', max_length=2)),
                ('tissue_specificity', models.CharField(blank=True, default='', max_length=3)),
                ('family_member', models.CharField(blank=True, default='', max_length=20)),
                ('tsi_hd', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True)),
                ('tsi_kd', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True)),
                ('tsi_nd', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TSI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tsi', models.FloatField()),
            ],
        ),
    ]
