# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class TSI(models.Model):
    name = models.CharField(max_length=100)
    tsi = models.FloatField()
    def __str__(self):
        return self.name
        
class Keyminer(models.Model):
    ''' Autogenerated model file csvimport Mon Aug 27 02:15:54 2018 '''

    probeid= models.CharField(primary_key=True, default='', max_length=50, null=False, blank=False)
    name = models.CharField(default='', max_length=30, null=False, blank=False)
    nmtsi = models.DecimalField(default=0, null=True, max_digits=20, decimal_places=10, blank=True)
    potential_regulatory_lineage = models.CharField(default='', max_length=2, blank=True)
    atsi = models.DecimalField(default=0, null=True, max_digits=20, decimal_places=10, blank=True)
    potential_tissue_specificity = models.CharField(default='', max_length=3, blank=True)
    hd0 = models.DecimalField(default=0, null=True, max_digits=8, decimal_places=4, blank=True)
    hd3 = models.DecimalField(default=0, null=True, max_digits=8, decimal_places=4, blank=True)
    hd6 = models.DecimalField(default=0, null=True, max_digits=8, decimal_places=4, blank=True)
    hd10 = models.DecimalField(default=0, null=True, max_digits=8, decimal_places=4, blank=True)
    kd0 = models.DecimalField(default=0, null=True, max_digits=8, decimal_places=4, blank=True)
    kd3 = models.DecimalField(default=0, null=True, max_digits=8, decimal_places=4, blank=True)
    kd6 = models.DecimalField(default=0, null=True, max_digits=8, decimal_places=4, blank=True)
    kd10 = models.DecimalField(default=0, null=True, max_digits=8, decimal_places=4, blank=True)
    nd0 = models.DecimalField(default=0, null=True, max_digits=8, decimal_places=4, blank=True)
    nd3 = models.DecimalField(default=0, null=True, max_digits=8, decimal_places=4, blank=True)
    nd6 = models.DecimalField(default=0, null=True, max_digits=8, decimal_places=4, blank=True)
    nd10 = models.DecimalField(default=0, null=True, max_digits=8, decimal_places=4, blank=True)
    specific_regulatory_linearge = models.CharField(default='', max_length=2, blank=True)
    tissue_specificity = models.CharField(default='', max_length=3, blank=True)
    family_member = models.CharField(default='', max_length=20, blank=True)
    tsi_hd = models.DecimalField(default=0, null=True, max_digits=20, decimal_places=10, blank=True)
    tsi_kd = models.DecimalField(default=0, null=True, max_digits=20, decimal_places=10, blank=True)
    tsi_nd = models.DecimalField(default=0, null=True, max_digits=20, decimal_places=10, blank=True)

    def __str__(self):
        return self.name

